package domain;

public enum Grade {
    KARDANI,
    KARSHENASI_PEYVASTEH,
    KARSHENASI_NAPEYVASTEH,
    KARSHENASI_ARSHAD_PEYVASTEH,
    KARSHENASI_ARSHAD_NAPEYVASTEH,
    PHD_PEYVASTEH,
    PHD_NAPEYVASTEH,
    PHD_SPECIALIZED
}
